import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav-bar";

const sora = Sora({
  subsets: ["latin"],
  weight: ['100', '400', '500', '600', '700', '800'],
  variable: "--font-sora",

});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
