import { Navbar } from "@/components/nav-bar";
import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import Footer from "@/components/custom/footer";

const unbounded = Unbounded({
  subsets: ["latin"],
  weight: ["200", "300", '400', '500', '600', '700', '800', "900"],
  variable: "--font-sora",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.className} antialiased bg-[#f5f5f5]`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
